#!/bin/bash

CACHE_DIR="${HOME}/.cache/squash"
THEME_DIR="${HOME}/.config/squash"
VIM_CONFIG="${HOME}/.config/nvim/appearance.vim"
TWOBWM_PATH="${HOME}/2bwm/src/2bwm"
BSPWM_PATH="${HOME}/.config/bspwm"
