#!/bin/bash


if [ ! -d ~/.config/squash ]; then
	mkdir ~/.config/squash
fi

if [ ! -d ~/.config/squash/themes ]; then
	mkdir ~/.config/squash/themes
fi

if [ ! -d ~/.config/squash/config ]; then
	mkdir ~/.config/squash/config
fi

if [ ! -d ~/.config/squash/generic ]; then
	mkdir ~/.config/squash/generic
fi

cp ~/squash/themes/* ~/.config/squash/themes/
cp ~/squash/config/* ~/.config/squash/config/
