#!/usr/bin/env bash
#
# Simple bash script used to dynamically reload
# all open instances of neovim by sourcing $MYVIMRC
# without having to restart
#
# REQUIRED: nvr-remove must be installed

if [[ ! $(command -v nvr) ]]; then
    printf "Error:: neovim-remote not found\n"
    printf "Please install nvr to reload neovim\n"
else
    inst=($(nvr --serverlist | grep nvim | sort | uniq))

    for nvim_inst in "${inst[@]}"; do 
        nvr --servername "${nvim_inst}" --remote-send '<Esc>:so ${HOME}/.config/nvim/init.vim<CR>' &
    done
fi
