#!/bin/bash

COLORS="$1"
FILE_PATH=~/.local/share/themes/generic/openbox-3/themerc
. ~/.config/themes/${COLORS}.config

rm -f ${FILE_PATH}

# get colors from crayolo
BG="$(xrdb -query | grep ${BACKGROUND} | cut -d ":" -f 2 | tr -d '[:space:]')"
FG="$(xrdb -query | grep ${FOREGROUND} | cut -d ":" -f 2 | tr -d '[:space:]')"
AC="$(xrdb -query | grep ${ALTERNATE} | cut -d ":" -f 2 | tr -d '[:space:]')"

# define menu colors
MENU_A_BG=${BG}
MENU_A_TEXT=${AC}
MENU_BG=${BG}
MENU_BORDER=${BG}
MENU_SEPERATOR=${BG}
MENU_TITLE_BG=${BG}
MENU_TITLE_TEXT=#eee

# define osd colors
OSD_BG=${BG}
OSD_TEXT=${BG}

# define active window colors
WINDOW_A_BG=${AC}
WINDOW_A_BG_BUTTON=${AC}
WINDOW_A_H_BUTTON=${BG}
WINDOW_A_P_BUTTON=${BG}
WINDOW_A_T_BUTTON=${BG}
WINDOW_A_U_BUTTON=${BG}

# devine inactive window colors
WINDOW_I_BG=${BG}
WINDOW_I_BG_BUTTON=${BG}
WINDOW_I_H_BUTTON=${AC}
WINDOW_I_T_BUTTON=${BG}
WINDOW_I_U_BUTTON=${BG}

cat > ${FILE_PATH} << EOL
# titlebars
border.width: 0
padding.height: 10
padding.width: 7

# menu
menu.items.active.bg: Solid Flat
menu.items.active.bg.color: ${MENU_A_BG}
menu.items.active.text.color: ${MENU_A_TEXT}
menu.items.bg: Flat Solid
menu.items.bg.color: ${MENU_BG}
menu.items.disabled.text.color: #666
menu.items.text.color: #eee
menu.border.width: 15
menu.border.color: ${MENU_BORDER}
menu.separator.color: ${MENU_SEPERATOR}
menu.title.bg: Solid Flat
menu.title.bg.color: ${MENU_TITLE_BG} 
menu.title.text.color: #eee
menu.title.text.justify: Center

# osd
osd.bg: Solid Flat
osd.bg.color: ${OSD_BG}
osd.label.text.color: ${OSD_TEXT}
 
# windows
window.client.padding.width: 0
window.handle.width: 0
 
# active window
window.active.*.bg: Solid Flat
window.active.*.bg.color: ${WINDOW_A_BG} 
window.active.button.*.bg.color: ${WINDOW_A_BG_BUTTON}
window.active.button.hover.image.color: ${WINDOW_A_H_BUTTON}
window.active.button.pressed.image.color: ${WINDOW_A_P_BUTTON}
window.active.button.toggled.image.color: ${WINDOW_A_T_BUTTON}
window.active.button.unpressed.image.color: ${WINDOW_A_U_BUTTON}
 
# inactive window
window.inactive.*.bg: Solid Flat
window.inactive.*.bg.color: ${WINDOW_I_BG}
window.inactive.button.*.bg.color: ${WINDOW_I_BG_BUTTON}
window.inactive.button.hover.image.color: ${WINDOW_I_H_BUTTON}
window.inactive.button.toggled.image.color: ${WINDOW_I_T_BUTTON}
window.inactive.button.unpressed.image.color: ${WINDOW_I_U_BUTTON}
EOL

cat ${FILE_PATH}
