#!/usr/bin/env bash

# COLORSCHEME 
COLOR_SCHEME="$1"

# GLOBAL VARIABLES
CACHE_DIR=$HOME/.cache/squash
THEME_DIR=$HOME/.config/squash
VIM_CONFIG=$HOME/.config/nvim/appearance.vim
WM=$(head -n 1 $CACHE_DIR/wm)

# CONVENIENCE VARIABLES
NEWLINE=$'\n'
sequence=""

# Removes old color files from the cache
# directory used to define xrdb
cleanup() { 
   rm -f $CACHE_DIR/x_colors
}

# Sends the current color escape sequences to 
# all active terminals, causing them to 
# change active colors without having to be
# reloaded
reload_x() { 
   for term in /dev/pts/[0-9]*; do
      printf "%b" "$sequence" > "$term"
   done
}

# Reloads the current X resources file
# in the home direcotry
merge_x() { 
   xrdb ${HOME}/.Xresources
}

reload_lemonbar() { 
    killall lemonbar
    bar &
}

# Credit for this method goes to dkeg
# github.com/dkeg
# Changes the colors within 2bwm's config.h file
# to reflect the new colorscheme, then recompiles and
# reloads 2bwm
# NOTE: Requires sudo
reload_2bwm() { 
   foc=$ylw
   unfoc=$blu
   fixc=$red
   unkil=$cyn
   fixunk=$mag
   outr=$bg
   emp=$bg

   dir=$HOME/2bwm/src/2bwm
   file=$dir/config.h

   #printf "${NEWLINE}"
   #printf "${dir}${NEWLINE}"
   #printf "${file}${NEWLINE}"

   wmcol=$(cat $file|awk '/\*colors/ {print $6}'|cut -d '}' -f1|awk '{gsub(/"/," ");print $2,$4,$6,$8,$10,$12,$14}') 
   arr=($wmcol)

    sed -i "s/${arr[0]}/"$foc"/;
            s/${arr[1]}/"$unfoc"/;
            s/${arr[2]}/"$fixc"/;
            s/${arr[3]}/"$unkil"/;
            s/${arr[4]}/"$fixunk"/;
            s/${arr[5]}/"$outr"/;
            s/${arr[6]}/"$emp"/" $file 

   cd $dir && make && sudo make install && cd

   xdotool key "super+ctrl+r"
}

# Sets the current wallpaper using hsetroot. 
# Overwrites any current wallpaper set by either
# xsetroot or nitrogen
set_wallpaper() { 
   hsetroot -fill ${wallpaper}
   cp ${wallpaper} "/tmp/screen.png"
}

# builds an array of all necessary colors
# the last three elements of the array are
# the bg, fg, and cursor color
get_colors() { 
   . $THEME_DIR/$COLOR_SCHEME
   COLOR_ARRAY=($blk $red $grn $ylw $blu $mag $cyn $wht \
                $bblk $bred $bgrn $bylw $bblu $bmag $bcyn $bwht)
}
# adds main colors to sequence 0-15. Colors are defined in the 
# COLOR_ARRAY
create_main_sequence() { 
   for i in {0..15}; do
      sequence+="\033]4;${i};${COLOR_ARRAY[${i}]}\007"
   done
}

# adds background and foreground colors to sequence
# does not rely on array, uses sourced variables
create_secondary_sequence() { 
   # add foreground
   for i in 10 12 13; do
      sequence+="\033]${i};${fg}\007"
   done

   # add background
   for i in 11 14 708; do
      sequence+="\033]${i};${bg}\007"
   done
}

write_x_source() { 
   x_output=""
   x_output+="*.foreground:   ${fg}${NEWLINE}"
   x_output+="*.background:   ${bg}${NEWLINE}"
   x_output+="*.cursorColor:  ${fg}${NEWLINE}"

   for i in {0..15}; do
      x_output+="*.color${i}: ${COLOR_ARRAY[${i}]}${NEWLINE}"
   done
}

write_rofi() { 

   rofi_output=""
   rofi_output+="rofi.color-enaled: true${NEWLINE}"
   rofi_output+="rofi.color-window: ${bg}, ${bg}, ${blk}${NEWLINE}"
   rofi_output+="rofi.color-normal: ${bg}, ${fg}, ${bg}, ${blk}, ${acc}${NEWLINE}"
}

write_2bwm() { 
   twobwm_output=""
   twobwm_output+="twobwm.focus_color: ${wht}${NEWLINE}"
   twobwm_output+="twobwm.unfocus_color: ${blu}${NEWLINE}"
   twobwm_output+="twobwm.fixed_color: ${wht}${NEWLINE}"
   twobwm_output+="twobwm.unkill_color: ${wht}${NEWLINE}"
   twobwm_output+="twobwm.outer_border_color: ${bg}${NEWLINE}"
   twobwm_output+="twobwm.fixed_unkill_color: ${cyn}${NEWLINE}"
}

# Writes CSS colors for use with programs such as firefox to 
# $CACHE_DIR/colors.css
write_css() { 
   css_output=""
   css_output+=":root {${NEWLINE}"
   css_output+="\t--wallpaper: url("${wallpaper}");${NEWLINE}"
   css_output+="\t--background: ${bg};${NEWLINE}"
   css_output+="\t--foreground: ${fg};${NEWLINE}"
   for i in {0..15}; do
      css_output+="\t--color${i}: ${COLOR_ARRAY[${i}]};${NEWLINE}"
   done
   css_output+="}"
   printf "${css_output}" > "${CACHE_DIR}/colors.css"
}

# Writes SH Colors for use with programs such as lemonbar
# to $CACHE_DIR/colors
write_sh() { 
   rm -f $CACHE_DIR/colors
   cp $THEME_DIR/$COLOR_SCHEME $CACHE_DIR/colors
}

# Writes X Output, Rofi output, and 2bwm output to x_colors
# in $CACHE_DIR
write_all_x() { 
   output=${x_output}${rofi_output}${twobwm_output}
   printf "${output}" > "${CACHE_DIR}/x_colors"
}

write_x_define() { 
   xd_output=""
   xd_output+="#define bg   ${bg}${NEWLINE}"
   xd_output+="#define blk   ${blk}${NEWLINE}"
   xd_output+="#define bblk   ${bblk}${NEWLINE}"
   xd_output+="#define fg   ${fg}${NEWLINE}"
   xd_output+="#define red   ${red}${NEWLINE}"
   xd_output+="#define bred   ${bred}${NEWLINE}"
   xd_output+="#define grn   ${grn}${NEWLINE}"
   xd_output+="#define bgrn   ${bgrn}${NEWLINE}"
   xd_output+="#define ylw   ${ylw}${NEWLINE}"
   xd_output+="#define bylw   ${bylw}${NEWLINE}"
   xd_output+="#define blu   ${blu}${NEWLINE}"
   xd_output+="#define bblu   ${bblu}${NEWLINE}"
   xd_output+="#define mag   ${mag}${NEWLINE}"
   xd_output+="#define bmag   ${bmag}${NEWLINE}"
   xd_output+="#define cyn   ${cyn}${NEWLINE}"
   xd_output+="#define bcyn   ${bcyn}${NEWLINE}"
   xd_output+="#define wht   ${wht}${NEWLINE}"
   xd_output+="#define bwht   ${bwht}${NEWLINE}"

   printf "${xd_output}" > "$CACHE_DIR/xd_colors"
}

write_name() {
    printf "$COLOR_SCHEME" > "${CACHE_DIR}/name"
}

write_vim_colorscheme() {
    sed -i -e "s/colorscheme .*/colorscheme $vim_scheme/g" $VIM_CONFIG
}

if [ -f $THEME_DIR/$COLOR_SCHEME ]; then
    printf "Changing colorschemes..."

    # Remove old colors
    cleanup

    # Source color directory
    get_colors

    # Create sequence to reload opened terminals
    create_main_sequence
    create_secondary_sequence

    # Reload all x terminals
    reload_x

    # Write all colors files to .cahe
    write_x_source
    write_rofi
    write_2bwm
    write_all_x
    write_css
    write_sh
    write_x_define
    write_name
    write_vim_colorscheme

    # Merge x colors
    merge_x

    reload_lemonbar

    # Set wallpaper
    set_wallpaper

    # Recompile and reload 2bwm
    # Reload bar
    if [[ $WM == "2bwm" ]]; then
        reload_2bwm
    fi
else
    printf "ERROR: THEME FILE NOT FOUND"
fi
