#!/usr/bin/env bash

source "${HOME}/.cache/squash/colors"
BAR_NAME="${1}"

FONTS="-f -uw-ttyp0-medium-r-normal-*-14-*-*-*-*-*-*-* -f -*-siji-*"
WIDTH=1910
HEIGHT=20
XOFF=0
YOFF=0
BRDR=5 # border width
BRDRC=${BG} # border color
BBG=${BG} # bar background color
#BBG=#00000000 #back background transparent
BFG=${FG}

SEP="  "
SEP2="    "
SEPB="__"
SPC="%{B$BG}%{F$BG}$SEPB%{B-}%{F-}"

GLYCUR=$(echo -e "\ue000")
GLYEM=$(echo -e "\ue001")
GLYDATE=$(echo -e "\ue015")
GLYVOL=$(echo -e "\ue050")
GLYVOLoff=$(echo -e "\ue052")
GLYBATLOW=$(echo -e "\ue035")
GLYBAT=$(echo -e "\ue037")
GLYBATMAX=$(echo -e "\ue09e")
GLYWLANHIGH=$(echo -e "\ue048")
GLYWLANLOW=$(echo -e "\ue047")

if [[ "${BAR_NAME}" == "blockbar" ]]; then
    PANIC="%{F$MAG}%{B$BBLK}${SEP}"
    ALERT="%{F$RED}%{B$BBLK}${SEP}"
    WARN="%{F$YLW}%{B$BBLK}${SEP}"
    GOOD="%{F$GRN}%{B$BBLK}${SEP}"
    PLAIN="%{F$WHT}%{B$BBLK}${SEP}"
    GEN="%{F$FG}%{B$BBLK}${SEP}"
    EMPTY="%{F$FG}%{B$BBLK}${SEP}"
    BLACK="%{F$FG}%{B$BLK}${SEP}"
    FULL="%{F$BLK}%{B$ACC}${SEP}"
    CLR="${SEP}%{B-}${F-}"

    if [ ! -z ${LMNBAR_DARK} ]; then
        PANIC="%{F$MAG}%{B$LMNBAR_DARK}${SEP}"
        ALERT="%{F$RED}%{B$LMNBAR_DARK}${SEP}"
        WARN="%{F$YLW}%{B$LMNBAR_DARK}${SEP}"
        GOOD="%{F$GRN}%{B$LMNBAR_DARK}${SEP}"
        PLAIN="%{F$WHT}%{B$LMNBAR_DARK}${SEP}"
        GEN="%{F$FG}%{B$LMNBAR_DARK}${SEP}"
        EMPTY="%{F$FG}%{B$LMNBAR_DARK}${SEP}"
        BLACK="%{F$FG}%{B$LMNBAR_DARKER}${SEP}"
        FULL="%{F$BLK}%{B$ACC}${SEP}"
    fi
elif [[ "${BAR_NAME}" == "simplebar" ]]; then
    PANIC="%{F$MAG}%{B$BG}${SEP}"
    ALERT="%{F$RED}%{B$BG}${SEP}"
    WARN="%{F$YLW}%{B$BG}${SEP}"
    GOOD="%{F$GRN}%{B$BG}${SEP}"
    PLAIN="%{F$WHT}%{B$BG}${SEP}"
    GEN="%{F$FG}%{B$BG}${SEP}"
    EMPTY="%{F$FG}%{B$BG}${SEP}"
    BLACK="%{F$FG}%{B$BG}${SEP}"
    FULL="%{F$ACC}%{B$BG}${SEP}"
    CLR="${SEP}%{B-}${F-}"

    if [ ! -z ${LMNBAR_DARK} ]; then
        PANIC="%{F$MAG}%{B$BG}${SEP}"
        ALERT="%{F$RED}%{B$BG}${SEP}"
        WARN="%{F$YLW}%{B$BG}${SEP}"
        GOOD="%{F$GRN}%{B$BG}${SEP}"
        PLAIN="%{F$WHT}%{B$BG}${SEP}"
        GEN="%{F$FG}%{B$BG}${SEP}"
        EMPTY="%{F$FG}%{B$BG}${SEP}"
        BLACK="%{F$FG}%{B$BG}${SEP}"
        FULL="%{F$ACC}%{B$BG}${SEP}"
    fi
fi
