#!/usr/bin/env bash
#
# -- infobar2: minimal block-style bar for use with lemonbar
# -- Author  : Joshua L Ervin @ Unversity of Washington
# -- Contant : jlervin@posteo.net

BAR_NAME="blockbar"
source ${HOME}/squash/bar/bar_defaults "${BAR_NAME}"

# Bar contents
content() 
{
    # Get current workspaces
    # Displays the active workspace using a 0 index
    # Notes:
    #   Requires xprop to get current desktop
    #   For windochef to function properly, 
    #   windows must be assigned to groups
    workspaces() {
        local cur=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
        local total=5
        local seq=""

        for ((i=0; i<${cur} && i<$((${total}-1)); i++)); do 
            seq+="${EMPTY}${i}"
        done

        seq+="${SEP}${FULL}${cur}${SEP}"

        for ((i=$((${cur}+1)); i<$total; i++)); do
            seq+="${EMPTY}${i}"
        done

        echo "${seq}${CLR}"
    }

    # Clock function gets current time and displays
    # Day of week, date, and time
    date-time() 
    {
        local clock="$(date +'%a %d %I:%M')"
        echo "${GEN}${GLYDATE}${SEP}${BLACK}${clock}${CLR}"
    }

    # Volume 0-100
    # Glyph will change when volume is muted
    # Notes:
    #   Requires amixer to get volume
    volume() 
    {
        local vol="$(amixer get Master|awk 'NR==5 {print $4}'|cut -d '%' -f1 | cut -d '[' -f2)"
        local mut="$(amixer get Master| awk 'NR==5 {print $6}')"

        if [[ ${mut} = "[off]" ]]; then
            echo "${ALERT}${GLYVOL}${SEP}${BLACK}${vol}${CLR}"
        elif [[ ${vol} = 0 ]]; then
            echo "${WARN}${GLYVOL}${SEP}${BLACK}${vol}${CLR}"
        else
            echo "${GOOD}${GLYVOL}${SEP}${BLACK}${vol}${CLR}"
        fi
    }

    # Battery 0-100
    # Battery considered charged at 98%
    # Glyph changes below 20 %
    battery() 
    {
        local cap="$(cat /sys/class/power_supply/BAT0/capacity)"
        local stat="$(cat /sys/class/power_supply/BAT0/status)"

        if [[ ${cap} -ge 98 || ${stat} = "Charging" ]]; then
            echo "${GOOD}${GLYBATMAX}${SEP}${BLACK}${cap}${CLR}"
        elif [[ ${cap} -ge 50 ]]; then
            echo "${WARN}${GLYBAT}${SEP}${BLACK}${cap}${CLR}"
        else 
            echo "${ALERT}${GLYBATLOW}${SEP}${BLACK}${cap}${CLR}"
        fi
    }

    # Get SSID using iwgetid
    # If iwgetid is not found, then DISCONNECTED will be displayed
    wireless() 
    {
        local wifi=$(iwgetid -r)

        if [[ -z $wifi ]]; then
            local wifi="DISCONNECTED"
            echo "${ALERT}${GLYWLANLOW}${SEP}${BLACK}${wifi}${CLR}"
        else
            echo "${GOOD}${GLYWLANHIGH}${SEP}${BLACK}${wifi}${CLR}"
        fi
    }

    # Bar contents left/right
    local left="$(workspaces)"
    local center=
    local right="$(wireless)"${SEP2}"$(battery)"$SEP2"$(volume)"$SEP2"$(date-time)"
    local output="${left}%{c}${center}%{r}${right}"

    echo -n "${output}"
}

content

# Final output formatting
options="-d ${FONTS} -g ${WIDTH}x${HEIGHT}+${XOFF}+${YOFF} -B ${BBG} -F ${BFG} -r 5 -R ${BRDRC}" 

# Main loop
while true; do
    echo $(content)
    sleep .5
done | lemonbar ${options} | sh > /dev/null 2>&1
