#!/usr/bin/env bash

bg=#181818
fg=#d8d8d8

blk=#181818
red=#ab4642
grn=#a1b56c
ylw=#f7ca88
blu=#7cafc2
mag=#ba8baf
cyn=#86c1b9
wht=#d8d8d8

bblk=#585858
bred=#dc9656
bgrn=#282828
bylw=#383838
bblu=#b8b8b8
bmag=#e8e8e8
bcyn=#a16946
bwht=#f8f8f8

acc=$red

wallpaper='~/Wallpapers/windows.jpg'
wallpaper_style='fill'
vim_scheme='base16-default-dark'
bar='bar'

