#!/usr/bin/env bash



bg=#2c2a2b
fg=#bab9ba
blk=#2d2b2c
bblk=#545253
red=#a67979
grn=#809f7b
ylw=#baad8a
blu=#6d7575
mag=#7d6969
cyn=#7b9899
wht=#bab9ba
bred=#a67979
bgrn=#809f7b
bylw=#baad8a
bblu=#6d7575
bmag=#7d6969
bcyn=#7b9899
bwht=#bab9ba
wallpaper=~/wallpapers/5i43Hvw.jpg
