#!/usr/bin/env bash





bg=#272a2a
fg=#eaeaed
blk=#282c2c
bblk=#484c4e
red=#b05f5f
bred=#b05f5f
grn=#88aa55
bgrn=#88aa55
ylw=#ccb05f
bylw=#ccb05f
blu=#556973
bblu=#556973
mag=#80807e
bmag=#80807e
cyn=#558888
bcyn=#558888
wht=#eaeaed
bwht=#f6f7f8
wallpaper=~/wallpapers/5i43Hvw.jpg
