#!/usr/bin/env bash




bg=#32221a
fg=#cfc1a9
blk=#35241c
bblk=#564a45
red=#c2562d
grn=#96a65e
ylw=#d29b5a
blu=#3b8e8c
mag=#c47e5b
cyn=#639a90
wht=#cfc1a9
bred=#c2562d
bgrn=#96a65e
bylw=#d29b5a
bblu=#3b8e8c
bmag=#c47e5b
bcyn=#639a90
bwht=#cfc1a9
wallpaper=~/wallpapers/5i43Hvw.jpg
