#!/usr/bin/env bash




bg=#1f1d1d
fg=#ccbaad
blk=#201e1e
bblk=#4a4a4a
red=#6b4747
grn=#8d7138
ylw=#856237
blu=#3c3c49
mag=#3c342e
cyn=#5d5a4b
wht=#ccbaad
bred=#6b4747
bgrn=#8d7138
bylw=#856237
bblu=#3c3c49
bmag=#3c342e
bcyn=#5d5a4b
bwht=#eae2dc
wallpaper=~/wallpapers/5i43Hvw.jpg
