#!/usr/bin/env bash




bg=#1c2319
fg=#bcbebb
blk=#1d241a
bblk=#35422f
red=#c14d38
grn=#a0ce52
ylw=#be9e61
blu=#4c7e89
mag=#814d61
cyn=#79a69d
wht=#bcbebb
bred=#c14d38
bgrn=#a0ce52
bylw=#be9e61
bblu=#4c7e89
bmag=#814d61
bcyn=#79a69d
bwht=#bcbebb
wallpaper=~/wallpapers/5i43Hvw.jpg
