#!/usr/bin/env bash



bg=#262c1b
fg=#c1c5bd
blk=#29301d
bblk=#474c3e
red=#7f5545
grn=#677c54
ylw=#bba772
blu=#6e6a5b
mag=#92887e
cyn=#7c7562
wht=#cccdbd
bred=#7f5545
bgrn=#6b9c25
bylw=#d6caaa
bblu=#6e6a5b
bmag=#92887e
bcyn=#7c7562
bwht=#e0e1d7
wallpaper=~/wallpapers/5i43Hvw.jpg
