#!/usr/bin/env bash

bg=#2c3e50
fg=#e0e0e0

blk=#2c3e50
red=#e74c3c
grn=#2ecc71
ylw=#f1c40f
blu=#3498db
mag=#9b59b6
cyn=#1abc9c
wht=#e0e0e0

bblk=#95a5a6
bred=#e74c3c
bgrn=#2ecc71
bylw=#f1c40f
bblu=#3498db
bmag=#9b59b6
bcyn=#1abc9c
bwht=#ecf0f1

acc=$red

wallpaper=~/Wallpapers/windows.jpg
vim_scheme=base16-flat

