#!/bin/bash
#
# Inspired by NerdyPepper
# github.com/NerdyPepper

#bg=#0c1014
bg=#090100
fg=#99d1ce

blk=#0c1014
red=#c23127
grn=#2aa889
ylw=#edb443
blu=#195466
mag=#4e5166
cyn=#33859E
wht=#99d1ce

bblk=#11151c
bred=#d26937
bgrn=#091f2e
bylw=#1e6479
bblu=#0a3749
bmag=#888ca6
bcyn=#599cab
bwht=#d3ebe9

acc=$red

wallpaper=~/wallpapers/viuxks.png
