#!/bin/bash

bg=#1d2021
fg=#ebdbb2

blk=#3c3836
red=#cc241d
grn=#98971a
ylw=#d79921
blu=#458588
mag=#b16286
cyn=#689d6a
wht=#fbf1c7

bblk=#3c3836
bred=#fb4934
bgrn=#b8bb26
bylw=#fabd2f
bblu=#83a598
bmag=#d3869b
bcyn=#8ec07c
bwht=#fbf1c7

acc=$ylw

wallpaper=~/wallpapers/sergey-turkin-299295.jpg
