#!/usr/bin/env bash


bg=#272733
fg=#cac5b7
blk=#292935
bblk=#48485e
red=#d65f2f
grn=#aabf7f
ylw=#dabe72
blu=#5e7e9b
mag=#bf6c68
cyn=#5a7273
wht=#cac5b7
bred=#d65f2f
bgrn=#aabf7f
bylw=#dabe72
bblu=#5e7e9b
bmag=#bf6c68
bcyn=#5a7273
bwht=#d5d1c6
wallpaper=~/wallpapers/5i43Hvw.jpg
