#!/bin/bash
#
# Inspired by xmiah 

bg=#28312E
fg=#C7DECA

blk=#28312e
red=#6A9176
grn=#66a575
ylw=#6B8482
blu=#72A08A
mag=#78C48E
cyn=#8CB096
wht=#C7DECA

bblk=#8B9B8D
bred=#6A9176
bgrn=#66A575
bylw=#6B8482
bblu=#72A08A
bmag=#78C48E
bcyn=#8CB096
bwht=#C7DECA

acc=$grn

wallpaper=~/wallpapers/sergey-turkin-299295.jpg
