#!/bin/bash
#
#Inspiredbydkeg
#github.com/dkeg

fg=#E8DFD6
bg=#021B21
blk=#032C36
bblk=#065F73
red=#C2454E
bred=#EF5847
grn=#7CBF9E
bgrn=#A2D9B1
ylw=#8A7A63
bylw=#BEB090
blu=#2E3340
bblu=#61778D
mag=#FF5879
bmag=#FF99A1
cyn=#44B5B1
bcyn=#9ED9D8
wht=#F2F1B9

acc=$cyn

wallpaper=~/wallpapers/jakob-owens-496354-unsplash.jpg
