#!/bin/bash

fg=#C7FEFE
bg=#0B2830
blk=#003549
bblk=#036495
red=#DA4B8E
bred=#F973B4
ylw=#C4BDBE
bylw=#F6E8EF
grn=#12677F
bgrn=#009BC2
blu=#004F77
bblu=#005490
mag=#CD4383
bmag=#EA7DB2
cyn=#00CDFE
bcyn=#37EDF7
wht=#C7FEFE
bwht=#fefefe

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/neon.png
