#!/usr/bin/env bash




bg=#241d1a
blk=#251e1b
fg=#c7b8ac
bblk=#50413a
red=#9f6434
grn=#9dac5f
ylw=#cca75f
blu=#2f7d7c
mag=#b5896e
cyn=#52877f
wht=#c7b8ac
bred=#9f6434
bgrn=#9dac5f
bylw=#cca75f
bblu=#2f7d7c
bmag=#b5896e
bcyn=#52877f
bwht=#c7b8ac
wallpaper=~/wallpapers/5i43Hvw.jpg
