#!/bin/bash

bg=#1A2B34
fg=#D8DEE9
blk=#1B2B34
bblk=#343D46
red=#EC5f67
grn=#99C794
ylw=#FAc863
blu=#5FB3B3
mag=#C594c5
cyn=#5FB3b3
wht=#CDD3DE
bred=#EC5f67
bgrn=#99C794
bylw=#FAc863
bblu=#5FB3B3
bmag=#C594c5
bcyn=#5FB3b3
bwht=#CDD3DE

acc0="#1A2B34"
acc1="#1A2B34"
acc2="#1A2B34"
acc3="#1A2B34"
acc4="#1A2B34"

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=/data/wallpapers/JKJhFUk.jpg
