#!/bin/bash

bg=#1A2B34
fg=#D8DEE9

blk=#1B2B34
red=#EC5f67
grn=#99C794
ylw=#FAc863
blu=#5FB3B3
mag=#C594c5
cyn=#5FB3b3
wht=#CDD3DE

bblk=#343D46
bred=#EC5f67
bgrn=#99C794
bylw=#FAc863
bblu=#5FB3B3
bmag=#C594c5
bcyn=#5FB3b3
bwht=#CDD3DE

acc=$red

wallpaper=~/wallpapers/jakob-owens-496354-unsplash.jpg
