#!/bin/bash

fg=#c5c8c6
bg=#121c21

blk=#1b2b34
red=#ec5f67
grn=#99c794
ylw=#dabe72
blu=#607a86
mag=#d1acd1
cyn=#8fbebe
wht=#d8dee9

bblk=#1b2b34
bred=#ec5f67
bgrn=#99c794
bylw=#dabe72
bblu=#607a86
bmag=#d1acd1
bcyn=#8fbebe
bwht=#d8dee9

acc=$red

wallpaper=~/wallpapers/das-sasha-24274-unsplash.jpg
