#!/usr/bin/env bash



bg=#2f2b2c
fg=#dedede
blk=#302c2c
bblk=#504c4e
red=#5a5a5a
grn=#989898
ylw=#cacaca
blu=#656565
mag=#b1b1b1
cyn=#7f7f7f
wht=#dedede
bred=#da5b2c
bgrn=#989898
bylw=#cacaca
bblu=#656565
bmag=#b1b1b1
bcyn=#7f7f7f
bwht=#FFFFFF
wallpaper=~/wallpapers/viuxks.png
