#!/bin/bash

bg=#232c33
fg=#f0f0f0
blk=#232c33
bblk=#70838c
red=#99736e
grn=#78a090
ylw=#bfb7a1
blu=#7c9fa6
mag=#BF9C86
cyn=#99BFBA
wht=#f0f0f0
bred=#99736e
bgrn=#78a090
bylw=#bfb7a1
bblu=#7c9fa6
bmag=#BF9C86
bcyn=#99BFBA
bwht=#f0f0f0

acc0="#7c9fa6"
acc1="#99BFBA"
acc2="#78a090"
acc3="#BF9C86"
acc4="#232c33"

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=/data/wallpapers/JKJhFUk.jpg
