#!/usr/bin/env bash

bg=#252a32
fg=#bab7b5

blk=#272c34
red=#876058
grn=#6f7f71
ylw=#b39580
blu=#546780
mag=#84787d
cyn=#556f86
wht=#bab7b5

bblk=#3b434f
bred=#876058
bgrn=#6f7f71
bylw=#b39580
bblu=#546780
bmag=#84787d
bcyn=#556f86
bwht=#dfdedd

acc=${red}

wallpaper=~/Wallpapers/skigh.png
vim_scheme='bleh'
bar='infobar'
