#!/usr/bin/env bash



bg=#2d3144
fg=#cfccbe
blk=#2f3447
bblk=#525a69
red=#8d6d5c
grn=#6d806d
ylw=#96915d
blu=#68758d
mag=#8a747b
cyn=#8d97a8
wht=#cfccbe
bred=#8d6d5c
bgrn=#6d806d
bylw=#96915d
bblu=#68758d
bmag=#8a747b
bcyn=#8d97a8
bwht=#f0efeb
wallpaper=~/wallpapers/5i43Hvw.jpg
