#!/usr/bin/env bash


!amodifiedversionofblok

bg=#2c373d
fg=#c4c0bb
blk=#2f393f
bblk=#4d5459
red=#a67979
grn=#809f7b
ylw=#baad8a
blu=#6d7575
mag=#8e7d79
cyn=#7b9899
wht=#c4c0bb
bred=#a67979
bgrn=#809f7b
bylw=#baad8a
bblu=#6d7575
bmag=#8e7d79
bcyn=#7b9899
bwht=#c4c0bb
wallpaper=~/wallpapers/5i43Hvw.jpg
