#!/bin/bash
#
#InspiredbyNerdyPepper
#github.com/NerdyPepper

fg=#C7C7C7
bg=#151515
blk=#393939
bblk=#474747
red=#FF9F95
bred=#FF8D80
grn=#9974C5
bgrn=#DBFFB3
ylw=#FFFFB9
bylw=#FFBE64
blu=#A351D6
bblu=#A020F0
mag=#E2B5B9
bmag=#D73A67
cyn=#F0205C
bcyn=:#DB6B8B
wht=#dddddd
bwht=#dddddd

acc=$red

wallpaper=~/wallpapers/annie-spratt-197810-unsplash.jpg
