#!/usr/bin/env bash
#
# Bash script to reload all active terminals by sending
# x escape sequences. 
#
# Args: A bash array where the indicies correspond to the color
#       code be used for X. 0 = black, 1 = red... etc
#       The last two indicies should correspond to the FG and BG
#
# Note: Not tested on non x-terminals (i.e. urxvt)

usage()
{
    printf "reload_terminals <COLOR_ARRAY>"
    exit 0
}

test -z ${1} && usage
COLOR_ARRAY=("$@")
SEQ=""

# Create main sequence for colors 0 - 15
for i in {0..15}; do 
    SEQ+="\033]4;${i};${COLOR_ARRAY[${i}]}\007"
done

# Support for background colors
for i in 10 12 13; do 
    SEQ+="\033]${i};${COLOR_ARRAY[17]}\007"
done

# Support for foreground colors
for i in 11 14 708; do 
    SEQ+="\033]${i};${COLOR_ARRAY[16]}\007"
done

for TERM in /dev/pts/[0-9]*; do
    printf "%b" "${SEQ}" > "${TERM}"
done
